/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jmatsu' at '15/10/21 4:44' with Gradle 2.7
 *
 * @author jmatsu, @date 15/10/21 4:44
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
